In [ ]:
import numpy as np

basic array creation

array generation function
random generation function
array attributes
array methods
reshaping and resizing

In [ ]:
a=[10,20,30,40,50]
a

[10, 20, 30, 40, 50]

In [ ]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr2=np.array(a)
arr2

array([10, 20, 30, 40, 50])

In [ ]:
l=np.array([[1,2,3,4,5],[6,7,8,9,10]])
l

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

array generation function

In [ ]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

we are creating an 2D array full of zeros

In [ ]:
np.zeros([4,8])

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones([5,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

random generation function

In [ ]:
np.random.rand(10)

array([0.60961962, 0.45550003, 0.1907001 , 0.38565708, 0.27756934,
       0.54291403, 0.2031762 , 0.83431021, 0.14370371, 0.65924032])

In [ ]:
np.random.randint(10,20,10)

array([12, 18, 18, 16, 11, 10, 16, 13, 10, 16])

In [ ]:
arr=np.array([[10,2],[0,30],[40,50]])
arr.dtype

dtype('int64')

ARRAY METHODS

In [6]:
import numpy as np

In [7]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
arr.sum()

np.int64(42)

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
arr.sum(axis=0)#agar axis=0 hai to column
              #agar axis=1 hai to rows

array([11, 14, 17])

In [11]:
arr.sum(axis=1)

array([ 6, 15, 21])

In [12]:
arr.mean()

np.float64(4.666666666666667)

In [13]:
arr.std()

np.float64(2.2110831935702664)

Reshaping and Resizing

In [15]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])