INDEXING
numpy indexing and slicing
numpy indexing and slicing(of a matrix)
Boolean indexing





NUMPY INDEXING AND SLICING

In [1]:
import numpy as np

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[5]
arr[-1]

np.int64(20)

In [4]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

numpy indexing and slicing(of a matrix)

In [11]:
arr=np.arange(1,31).reshape(6,5)
#arr[row_start:row_stop,col_start:col_stop]
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0,1]

np.int64(2)

In [12]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [13]:
arr[3:5,3]

array([19, 24])

In [14]:
arr[2:3,3:4]

array([[14]])

In [15]:
arr[2:,1:3]

array([[12, 13],
       [17, 18],
       [22, 23],
       [27, 28]])